import type { Metadata } from 'next'
import './globals.css'
import ICPAgentProvider from '@/components/icp-agent-provider'
import { ICPActorProvider } from '@/lib/actor'
import { dmSans } from '@/lib/font'
import Navbar from '@/components/layout/navbar'

export const metadata: Metadata = {
	title: 'TixChain',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${dmSans.variable} font-sans antialiased`}>
				<ICPAgentProvider withLocalEnv>
					<ICPActorProvider loadingComponent={null}>
						<main>
							<Navbar />
							{children}
						</main>
					</ICPActorProvider>
				</ICPAgentProvider>
			</body>
		</html>
	)
}
