import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ICPAgentProvider from '@/components/icp-agent-provider'
import { ICPActorProvider } from '@/lib/actor'

const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'ICP Ticket',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${inter.variable} font-sans antialiased`}>
				<ICPAgentProvider withLocalEnv>
					<ICPActorProvider loadingComponent={null}>{children}</ICPActorProvider>
				</ICPAgentProvider>
			</body>
		</html>
	)
}
